name: Trigger test
run-name: ${{ github.actor }} is testing out GitHub Actions on develop branch 🚀
on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:
    inputs:
      PROJECT_KEY:
        description: The key of project
        type: string
        required: true
      TEST_EXECUTION_KEY:
        description: The key of test execution
        type: string
        required: false

env:
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}

jobs:
  Trigger-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: export NODE_OPTIONS="--max-old-space-size=3072"
      - run: yarn install
      - run: yarn build
      # - run: yarn test
      - run: echo "success"
      - run: echo $CLIENT_ID
      - run: echo $CLIENT_SECRET
      - run: echo ${{ inputs.PROJECT_KEY }}
      - run: echo ${{ vars.PROJECT_KEY }}
      - run: echo ${{ inputs.TEST_EXECUTION_KEY }}
      - name: Log Owner, Repo, and Workflow ID
        run: |
          echo "Owner/Repo: ${{ github.repository }}"
          echo "Workflow Name: ${{ github.workflow }}"
          echo "Workflow Run ID: ${{ github.run_id }}"
      # - run: cat reports/junit.xml
      # - name: test
      #   run: |
      #     export token=$(curl 'https://dev.agiletest.atlas.devsamurai.com/api/apikeys/authenticate' -X POST -H 'Content-Type:application/json' --data '{"clientId":"'"$CLIENT_ID"'","clientSecret":"'"$CLIENT_SECRET"'"}' | tr -d '"')
      #     echo $token
      #     curl -H "Content-Type:text/xml" -H "Authorization:JWT $token" --data @reports/junit.xml "https://dev.api.agiletest.app/ds/test-executions/junit?projectKey=${{ inputs.PROJECT_KEY || vars.PROJECT_KEY }}&testExecutionKey=${{ inputs.TEST_EXECUTION_KEY }}"
      #     echo "done"
      - run: echo ${{ inputs.PROJECT_KEY }}
      - run: echo ${{ vars.PROJECT_KEY }}
      - name: After Script
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            RESULT="success"
          else
            RESULT="failed"
          fi

          # Get authentication token
          export token=$(curl 'https://kiet-le-dss-macbook-air.tail305ff.ts.net/api/apikeys/authenticate' -X POST -H 'Content-Type:application/json' --data '{"clientId":"xaIkb2y6ASAKJ15sfJYLZFKsxO9uoWZ2mOtXNEepyTk=","clientSecret":"015522653a0f81a9a7670c6840fc6a7f7d8ba8c1cea63489814fe5d877d2ac88"}' | tr -d '"')
          echo $token
          # Send the result data to the specified endpoint
          curl -H "Content-Type:application/json" -H "Authorization:JWT $token" --data '{ "tool":"github", "result":"'"$RESULT"'"  }' "https://kiet-le-dss-macbook-air.tail305ff.ts.net/ds/test-executions/${TEST_EXECUTION_KEY}/pipeline/history?projectKey=${PROJECT_KEY}"
