name: Trigger test
run-name: ${{ github.actor }} is testing out GitHub Actions on develop branch 🚀
on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:
    inputs:
      PROJECT_KEY:
        description: The key of project
        type: string
        required: true
      TEST_EXECUTION_KEY:
        description: The key of test execution
        type: string
        required: false
      milestoneId:
        description: The milestone id
        type: string
        required: false
      testPlanKeys:
        description: The test plan keys
        type: string
        required: false
      fixVersions:
        description: The fix versions
        type: string
        required: false
      testEnvironments:
        description: The test environments
        type: string
        required: false
      revision:
        description: The revision
        type: string
        required: false

env:
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}

jobs:
  Trigger-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: export NODE_OPTIONS="--max-old-space-size=3072"
      - run: yarn install
      - run: yarn build
      - name: Run tests
        run: yarn test
        continue-on-error: true
      - name: Upload test results to AgileTest
        run: |
          export token=$(curl 'https://kiets-macbook-air.tail305ff.ts.net/api/apikeys/authenticate' -X POST -H 'Content-Type:application/json' --data '{"clientId":"${{ env.CLIENT_ID }}","clientSecret":"${{ env.CLIENT_SECRET }}"}' | tr -d '"')
          curl -v -H "Content-Type:text/xml" -H "Authorization:JWT $token" --data @reports/junit.xml "https://kiets-macbook-air.tail305ff.ts.net/parser/ds/test-executions/junit?projectKey=${{ inputs.PROJECT_KEY || vars.PROJECT_KEY }}&testExecutionKey=${{ inputs.TEST_EXECUTION_KEY }}&milestoneId=${{ inputs.milestoneId }}&testEnvironments=${{ inputs.testEnvironments }}&testPlanKeys=${{ inputs.testPlanKeys }}&revision=${{ inputs.revision }}&fixVersions=${{ inputs.fixVersions }}"
